site_name: OSLA/VU Lab orchestrator

repo_url: https://github.com/OSLA-project/VU-lab
nav:
  - Home: index.md
  - Overview:
      - Inventory: overview/inventory.md
  - About:
      - Licence: about/licence.md
      - Contributing: about/contributing.md
      - Citation: about/citation.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: cyan

  features:
    - navigation.footer
  font:
    text: Roboto
    code: Roboto Mono
  locale: en
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_source: false
            group_by_category: false
            relative_crossrefs: true
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: true
      include_source: true
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
