name: test-compose.yml
on:
  push:
    branches:
      - main
      - 42-test-docker-compose-in-github-actions
  pull_request:

jobs:
  test-compose:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print os
        run: echo "Running on ${{ runner.os }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy linux env file
        if: runner.os == 'Linux'
        run: cp .env.linux.example .env

      - name: Copy Windows env file
        if: runner.os == 'Windows'
        run: cp .env.windows.simulated.example .env

      - name: Install wsl  on windows
        if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@v6

      - name: Check existence of .env file
        shell: bash
        run: |
          if [ ! -f .env ]; then
            echo ".env file does not exist!"
            exit 1
          else
            echo ".env file exists."
          fi

      - name: Start Docker Compose services
        run: docker compose up -d
        timeout-minutes: 2

      - name: Wait for services to stabilize. # Downloading images may take time
        run: sleep 60

      - name: Check service health
        run: |
          docker compose ps
          if docker compose ps | grep -E 'Exit|Restarting'; then
            echo "Service failed to start properly"
            docker compose logs
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: docker compose down -v