name: test-compose.yml
on:
  push:
    branches:
      - main
      - 42-test-docker-compose-in-github-actions
  pull_request:

jobs:
  test-compose:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print os
        run: echo "Running on ${{ runner.os }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy linux env file
        if: runner.os == 'ubuntu-22.04'
        run: cp .env.linux.example .env

      - name: Copy Windows env file
        if: runner.os == ' windows-2022'
        run: cp .env.windows.example .env

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Wait for services to stabilize
        run: sleep 30

      - name: Check service health
        run: |
          docker compose ps
          if docker compose ps | grep -E 'Exit|Restarting'; then
            echo "Service failed to start properly"
            docker compose logs
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: docker compose down -v